### ISSUE TITLE
User commands do not fire unless the mouse is over the urxvt window

### ISSUE THREAD

**Issue by smerrill** [stepb/urxvt-tabbedex#2]
Normally (without tabbed / tabbedex) user commands fire just fine if a urxvt window is in the foreground, regardless of whether or not the mouse is over the window.

However, with tabbed and tabbedex, the mouse must be over the window in order for user commands to fire.

I'm looking at how to fix this, but my Perl is exceptionally rusty, so if you had any pointers, I'd love to hear them.

**Comment by smerrill** [comment]
Closing, as pull request https://github.com/stepb/urxvt-tabbedex/issues/1 fixes this issue as well.

**Comment by vldmr** [comment]
Not working for me with tabbedex 0.3. 
I use rxvt-unicode-256color 9.10 on Debian Squeeze and rxvt-unicode-patched (http://aur.archlinux.org/packages.php?ID=44649) on Arch with awesome 3.4.9 (sloppy focus disabled).
