### ISSUE TITLE
tabbedex not working in Fedora 20 rxvt-unicode (urxvt) v9.19 - released: 2013-10-27

### ISSUE THREAD

**Issue by gomix** [stepb/urxvt-tabbedex#30]
In my Fedora 20 (beta) rxvt-unicode (urxvt) v9.19 - released: 2013-10-27:

$ urxvt -pe tabbedex
urxvt: perl hook 0 evaluation error: /usr/lib64/urxvt/perl/tabbedex: syntax error at /usr/lib64/urxvt/perl/tabbedex line 669, near "$hook qw(start destroy user_command key_press property_notify add_lines)"
syntax error at /usr/lib64/urxvt/perl/tabbedex line 681, near "}

}"

**Comment by yardenac** [comment]
This fixes it: https://github.com/stepb/urxvt-tabbedex/pull/23

**Comment by gomix** [comment]
Thanks, it does work now for me.
