### ISSUE TITLE
-geometry position ignored

### ISSUE THREAD

**Issue by himdel** [stepb/urxvt-tabbedex#39]
When I run `rxvt-unicode -geometry 105x55+3+30` with tabbedex, only the 105x55 portion is respected, the position is ignored. Removing tabbedex fixes it. I have no idea why that happens.

(This affects both the stepb version and the mina86 fork.)

**Comment by himdel** [comment]
Actually, even the size part is handled wrong:

Running `rxvt-unicode -geometry 80x25` and then `xwininfo` on the window yields `80x25` when tabbedex is off but `79x24` when on. So, an off by one somewhere?

**Comment by neilkatin** [comment]
I know this is an ancient bug, but I've been encountering the same bug.  I wanted to share that urxvt-tabbed has the same issue with ignoring window position, so it might be an 'upstream' bug that urxvt-tabbedex inherited.

**Comment by ernie-cordell** [comment]
Why is this still open?  I've tried a lot of things, but nothing works.  I know it is my fault, but what am I missing?  Posting files and options is useless since it may be anything. I'm on openSUSE Leap 42.3 with a 4.4.138-59-default kernel running an Xfce 4.12 window manager.

**Comment by mina86** [comment]
> Why is this still open?

This repository isn’t maintained.  See https://github.com/mina86/urxvt-tabbedex/.  Specifically regarding `-geometry` it got various fixes around that so it may work for you.  There’s still https://github.com/mina86/urxvt-tabbedex/issues/44 open so some issues remain.
