### ISSUE TITLE
Some resources like no-tabbedex-keys are not working

### ISSUE THREAD

**Issue by bstaletic** [stepb/urxvt-tabbedex#40]
Hello,

The following resources are not working:
URXvt.tabbed.reopen-on-close: true
URxvt.keysym.Control-Shift-Right: perl:tabbedex:move_tab_rightu
URxvt.keysym.Control-Shift-Left: perl:tabbedex:move_tab_left
URxvt.tabbed.no-tabbedex-keys: true

All other resources work as expected. I'm using rxvt-unicode 9.20-3, rxvt-tabbedex 0.4-4, rxvt-perls 2.1. My distro is Arch.

Here's the full .Xresources:
! Disable scrolling with output
URxvt_scrollTtyOutput: false
! scroll in relation to buffer (with mouse scroll or Shift+Page Up)
URxvt_scrollWithBuffer: true
! scroll back to the bottom on keypress
URxvt_scrollTtyKeypress: true
! Pager scrolling
URxvt.secondaryScreen: 1
URxvt.secondaryScroll: 0
! URL
URxvt.perl-ext-common:      default,tabbedex,clipboard,url-select,keyboard-select,matcher
URxvt.url-select.launcher:  /usr/bin/luakit
URxvt.url-select.underline: true
URxvt.keysym.M-u:           perl:url-select:select_next
URxvt.keysym.C-Escape:      perl:keyboard-select:activate
URxvt.keysym.C-s:           perl:keyboard-select:search
URxvt.url-launcher: /usr/bin/luakit
URxvt.matcher.button: 1
! Colors
URxvt_background: black
URxvt_foreground: white
URxvt.colorUL: #4682B4
! Fonts
URxvt_font: -_-terminus-medium-r-_-_-14-_-_-_-_-_-_-_
URxvt_boltfont:  -_-terminus-bold-r-_-_-14-_-_-_-_-_-_-*
! scrollbar style - rxvt (default), plain (most compact), next, or xterm
URxvt.scrollstyle: plain
URxvt_scrollBar: true
URxvt_scrollBar_right: true
! Colors
_color12:     #94bff3 
! Tabs
URxvt.tabbed.autohide: true
URxvt.keysym.Control-t: perl:tabbedex:new_tab
URxvt.keysym.Control-Tab: perl:tabbedex:next_tab
URxvt.keysym.Control-Shift-Tab: perl:tabbedex:prev_tab
! Clipboard
URxvt.keysym.C-C: perl:clipboard:copy
URxvt.keysym.C-V: perl:clipboard:paste
! Scrollback buffer
URxvt_saveLines: 1000
!! Does not work
URXvt.tabbed.reopen-on-close: true
URxvt.keysym.Control-Shift-Right: perl:tabbedex:move_tab_right
URxvt.keysym.Controlt-Shift-Left: perl:tabbedex:move_tab_left
URxvt.tabbed.no-tabbedex-keys: true
! Disable iso14755
URxvt.iso14755 : false

**Comment by mina86** [comment]
https://github.com/mina86/urxvt-tabbedex is repository that you are looking for.
